#cloud-config
manage_etc_hosts: true
user:
  - name: sysadmin
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ssh-rsa AAAAB3Nza... # Nhập Public SSH Key của bạn vào đây

package_update: true
package_upgrade: true
packages:
  - qemu-guest-agent
  - postgresql
  - postgresql-contrib

runcmd:
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
  # Cấu hình PostgreSQL lắng nghe tất cả các IP (hoặc dải IP của GCP)
  - sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/g" /etc/postgresql/14/main/postgresql.conf
  - echo "host all all 0.0.0.0/0 md5" >> /etc/postgresql/14/main/pg_hba.conf
  - systemctl restart postgresql